### ISSUE TITLE
fatal error in module: topola 

### ISSUE THREAD

**Issue by mostepunk** [PeWu/topola-webtrees#25]
Hi! Can somebody help me? I've just installed topola to webtrees 2.2.1 and I've got an error:
```
Fatal error in module: topola
Error: Call to undefined function LilaElephant\Webtrees\app() in /var/www/webtrees/modules_v4/topola/module.php:23 Stack trace: #0 /var/www/webtrees/app/Services/ModuleService.php(722): include() 
#1 /var/www/webtrees/app/Services/ModuleService.php(702): Fisharebest\Webtrees\Services\ModuleService::load('/var/www/webtre...') 
#2 [internal function]: Fisharebest\Webtrees\Services\ModuleService::Fisharebest\Webtrees\Services\{closure}('/var/www/webtre...', 0) 
#3 /var/www/webtrees/vendor/illuminate/collections/Arr.php(609): array_map(Object(Closure), Array, Array) 
#4 /var/www/webtrees/vendor/illuminate/collections/Collection.php(795): Illuminate\Support\Arr::map(Array, Object(Closure)) 
#5 /var/www/webtrees/app/Services/ModuleService.php(701): Illuminate\Support\Collection->map(Object(Closure)) 
#6 /var/www/webtrees/app/Services/ModuleService.php(624): Fisharebest\Webtrees\Services\ModuleService->customModules() 
#7 /var/www/webtrees/app/Cache.php(58): Fisharebest\Webtrees\Services\ModuleService->Fisharebest\Webtrees\Services\{closure}() 
#8 /var/www/webtrees/vendor/symfony/cache/Adapter/ArrayAdapter.php(81): Fisharebest\Webtrees\Cache::Fisharebest\Webtrees\{closure}(Object(Symfony\Component\Cache\CacheItem), true) 
#9 /var/www/webtrees/app/Cache.php(55): Symfony\Component\Cache\Adapter\ArrayAdapter->get('372b64b23390f9d...', Object(Closure)) 
#10 /var/www/webtrees/app/Services/ModuleService.php(616): Fisharebest\Webtrees\Cache->remember('all-modules', Object(Closure)) 
#11 /var/www/webtrees/app/Services/ModuleService.php(577): Fisharebest\Webtrees\Services\ModuleService->all(true) 
#12 /var/www/webtrees/app/Http/Middleware/UseLanguage.php(82): Fisharebest\Webtrees\Services\ModuleService->findByInterface('Fisharebest\\Web...', true) 
#13 /var/www/webtrees/app/Http/Middleware/UseLanguage.php(61): Fisharebest\Webtrees\Http\Middleware\UseLanguage->languages(Object(Nyholm\Psr7\ServerRequest)) 
#14 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLanguage->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #15 /var/www/webtrees/app/Http/Middleware/UseSession.php(79): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #16 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #17 /var/www/webtrees/app/Http/Middleware/UpdateDatabaseSchema.php(57): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #18 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #19 /var/www/webtrees/app/Http/Middleware/UseDatabase.php(60): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) 

#20 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #21 /var/www/webtrees/app/Http/Middleware/BadBotBlocker.php(308): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #22 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #23 /var/www/webtrees/app/Http/Middleware/CompressResponse.php(71): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #24 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CompressResponse->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #25 /var/www/webtrees/app/Http/Middleware/ContentLength.php(40): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #26 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ContentLength->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #27 /var/www/webtrees/vendor/middlewares/client-ip/src/ClientIp.php(65): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #28 /var/www/webtrees/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #29 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) 

#30 /var/www/webtrees/app/Http/Middleware/PublicFiles.php(62): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #31 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\PublicFiles->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #32 /var/www/webtrees/app/Http/Middleware/HandleExceptions.php(89): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #33 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #34 /var/www/webtrees/app/Http/Middleware/SecurityHeaders.php(49): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #35 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #36 /var/www/webtrees/app/Http/Middleware/BaseUrl.php(73): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #37 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #38 /var/www/webtrees/app/Http/Middleware/ReadConfigIni.php(68): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #39 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) 

#40 /var/www/webtrees/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) 
#41 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) 
#42 /var/www/webtrees/app/Http/Middleware/ErrorHandler.php(38): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) 
#43 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ErrorHandler->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) 
#44 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) 
#45 /var/www/webtrees/app/Webtrees.php(280): Middleland\Dispatcher->dispatch(Object(Nyholm\Psr7\ServerRequest)) 
#46 /var/www/webtrees/app/Webtrees.php(251): Fisharebest\Webtrees\Webtrees->httpRequest() 
#47 /var/www/webtrees/index.php(24): Fisharebest\Webtrees\Webtrees->run('apache2handler') 
#48 {main}
```

**Comment by arbor95** [comment]
this version is not compatible with wt 2.2:
Fatal error in module: topola
Error: Call to undefined function LilaElephant\Webtrees\app() in ....../webtrees/modules_v4/topola/module.php:23 Stack trace: #0

**Comment by mostepunk** [comment]
Is it fixable?

**Comment by arbor95** [comment]
you can try this appended file. It contains the obvious necessary changes (app( -> registry....).
[topola-2.1.0-for-wt2.2.zip](https://github.com/user-attachments/files/18227321/topola-2.1.0-for-wt2.2.zip)

**Comment by mostepunk** [comment]
> tell, if that works?!
This works fine, thanks a lot!
